<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\ameri\source\repos\BibliotecaApp\BibliotecaApp\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\ameri\source\repos\BibliotecaApp\BibliotecaApp\.editorconfig" />
  </ItemGroup>

</Project>